### ISSUE TITLE
[Bug] FILL_TITLE_HERE

### ISSUE THREAD

**Issue by dan-r95** [temporalio/cli#260]
### What are you really trying to do?

I wrote  a script to delete all workflows and schedules of a certain type (for example by customerId) via bash. Via this simple script I can delete all workflows easily. However the `temporal schedule delete -s  <id>` command fails. 

### Describe the bug
Listing all schedules works and returns their scheduleId, however deleting a schedule by its id throws the following error.
```
Error: unable to delete schedule: sql: no rows in result set
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/debug/stack.go:16 +0x19
github.com/temporalio/cli/app.HandleError(0x22dea80?, {0x335ed80, 0xc0000bab40})
	/home/runner/work/cli/cli/app/app.go:78 +0x15b
github.com/urfave/cli/v2.(*App).handleExitCoder(0xc0008a5900?, 0xc000872c00?, {0x335ed80?, 0xc0000bab40?})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:446 +0x38
github.com/urfave/cli/v2.(*Command).Run(0xc0008a5900, 0xc000876b80, {0xc000874420, 0x3, 0x3})

```

### Minimal Reproduction
following script fails:

```
echo "Removing all Workflows and Schedules from Temporal"

# List all schedules
schedule_list=$(temporal schedule list --output=json)

echo $schedule_list

# Extract schedule IDs
schedule_ids=$(echo "$schedule_list" | jq -r '.[] | .ScheduleId')

# Iterate through the extracted IDs and delete each schedule
for sid in $schedule_ids; do
  temporal schedule delete -s $sid
  sleep 0.25
done

# List all Workflow Executions
workflow_list=$(temporal workflow list --output=json)

# Extract Workflow IDs and Run IDs
workflow_ids=$(echo "$workflow_list" | jq -r '.[] | "\(.execution.workflow_id) \(.execution.run_id)"')

# Iterate through the extracted IDs and delete each Workflow Execution
while read -r workflow_id run_id; do
  temporal workflow delete --workflow-id "$workflow_id" --run-id "$run_id"
  sleep 0.25
done <<<"$workflow_ids"

``` 

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: VERSION:
   0.8.0 (server 1.20.1) (ui 2.13.3)
- Are you using Docker or Kubernetes or building Temporal from source?
  temporal docker - (auto-setup)

**Comment by dnr** [comment]
I just created a bunch of schedules and successfully deleted them using your script, using both a cassandra backend and a temporal cli dev server (0.9.0).

Do your schedule ids have whitespace or other shell metacharacters in them? That script isn't quoting everything super-thoroughly.
