### ISSUE TITLE
[Bug] nil deref during TestServer_StartDev_ConcurrentStarts test

### ISSUE THREAD

**Issue by josh-berry** [temporalio/cli#667]
Running `server start-dev` multiple times concurrently may occasionally cause a nil dereference to occur.

This was caught by CI. Example run: https://github.com/temporalio/cli/actions/runs/10855312160/job/30127644431?pr=658

Backtrace:

```
     commands_test.go:182: Calling: server start-dev -p 60743 --headless --log-level never
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xbaa90a]

goroutine 84720 [running]:
google.golang.org/grpc.(*Server).Serve(0xc002cae800, {0x0, 0x0})
	C:/Users/runneradmin/go/pkg/mod/google.golang.org/grpc@v1.65.0/server.go:864 +0x16a
go.temporal.io/server/service/matching.(*Service).Start.func1()
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.25.0/service/matching/service.go:103 +0x65
created by go.temporal.io/server/service/matching.(*Service).Start in goroutine 84691
	C:/Users/runneradmin/go/pkg/mod/go.temporal.io/server@v1.25.0/service/matching/service.go:101 +0x169
```

**Comment by chaptersix** [comment]
Closing as duplicate of #581. The nil deref is likely a symptom of the FailNow-from-goroutine issue described there.
